### ISSUE TITLE
pak::pkg_install is much faster

### ISSUE THREAD

**Issue by kwstat** [bbolker/mm_iowa2024#1]
I've recently been exploring the pak package for package management.
In your setup script, try this:
pak::pkg_install(all_pkgs)
Because of parallel downloads, it is much faster than built-in install.packages.

**Comment by bbolker** [comment]
Hmm.  That seems like a good idea in principle, although I'm a little bit nervous about this output when I run it myself, wanting to update several packages to what seem to be equivalent or even earlier versions ... I guess I don't understand how its metadata database works?

(For what it's worth there is some discussion of improving package download performance in base R, see [here](https://stat.ethz.ch/pipermail/r-devel/2024-April/083370.html) ...)

```r
→ Will update 5 packages.
→ Will download 4 CRAN packages (12.55 MB), cached: 1 (2.94 MB).
+ bbmle       1.0.25.1    → 1.0.25.1 [bld][dl] (529.03 kB)
+ broom.mixed 0.2.9.5     → 0.2.9.5  [bld][dl] (5.16 MB)
+ glmmTMB     1.1.9       → 1.1.9    [bld][cmp][dl] (4.36 MB)
+ lme4        1.1-35.9000 → 1.1-35.3 [bld][cmp]
+ performance 0.11.0.3    → 0.11.0   [bld][dl] (2.50 MB)
```

**Comment by bbolker** [comment]
have updated setup accordingly. Thanks.
