### ISSUE TITLE
INLA might need Bioconductor packages?

### ISSUE THREAD

**Issue by AaronRendahl** [bbolker/mm_iowa2024#4]
When installing INLA, it warns that it can't find `Rgraphviz` or `graph`; these seem to be on Bioconductor.

```
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install(c("Rgraphviz", "graph"))
```

The BiocManager install process also warns about two old packages, `prediction` and `survival`; when I tried updating them `survival` was able to be updated but `prediction` was not; apparently `update.packages()` thinks a newer version is available on CRAN but can't actually find it.  See more below.

In any case, if you want people to install these packages, perhaps best to recommend either "some" or "none" in the interactive prompt
`Update all/some/none? [a/s/n]: `
or simply to use the `update=FALSE` option

```
BiocManager::install(c("Rgraphviz", "graph"), update=FALSE)
```

About updating `prediction`, there's something odd, though, where 0.3.15 is installed (that's what's on github), it thinks 0.3.17 is on CRAN, but it tries to download 0.3.14.

```
prediction :
 Version 0.3.15 installed in /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library 
 Version 0.3.17 available at https://cran.rstudio.com
Update? (Yes/no/cancel) Yes
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.4/prediction_0.3.14.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.4/prediction_0.3.14.tgz'
```

**Comment by bbolker** [comment]
I think I might just bail on INLA.  I included it for completeness, but in all honesty (1) I'm much less familiar with it myself and (2) I don't think we'll get there.  I'm going to take it out of the instructions.

I think the issue with `prediction` is that MacOS binaries haven't been updated to version 3.17 yet? Honestly, `prediction` version shouldn't make any difference at all for this workshop.

**Comment by AaronRendahl** [comment]
thanks for looking into this!
